pathalias_extend.suffix.*:
  type: config_entity
  label: 'Pathalias Extend Suffix Configuration'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    status:
      type: boolean
      label: 'Status'
    target_entity_type_id:
      type: string
      label: 'Target Entity Type'
    target_bundle_id:
      type: string
      label: 'Target Bundle'
    pattern:
      type: string
      label: 'Pattern'
    create_alias:
      type: boolean
      label: 'Create Alias'
