<?php


function ph_commande_mail($key, &$message, $params) {
  switch ($key) {
    case 'commande_mail_key':
      $message['headers']['Content-Type'] = 'text/html; charset=UTF-8; format=flowed; delsp=yes';
      $message['subject'] = t('Commande - ').\Drupal::config('system.site')->get('name');;
      $message['body'][] = $params['body'];
      break;
  }
}

function ph_commande_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id)
{

//  die(var_dump(\Drupal\node\Entity\Node::load(16)->field_chat_messages));
  if ($form_id == "node_article_form") {
    phpinfo();
  }
  if ($form_id == "node_commande_form") {
    $user = \Drupal\user\Entity\User::load(\Drupal::currentUser()->id());
    if ($user->hasRole('pharmacie')) {
      $current_path = \Drupal::service("path.current")->getPath();
      $uid = explode("/", $current_path)[2];
      $grossiste = \Drupal\user\Entity\User::load($uid);
      if ($grossiste && $grossiste->hasRole('grossiste')) {
        $form['actions']['submit']['#submit'][] = 'assign_commande_to_grossiste';
      }
    }
  }
}

function assign_commande_to_grossiste(&$form, \Drupal\Core\Form\FormStateInterface $form_state)
{
  $node = \Drupal\node\Entity\Node::load($form_state->getValue('nid'));
  $current_path = \Drupal::service("path.current")->getPath();
  $uid = explode("/", $current_path)[2];
  $node->set('field_grossiste',  $uid);
  $node->save();


  $message = 'email body in <h2 style="color: red">html</h2>';

  $params = array(
    'subject' => t('Commande'),
    'body' => check_markup(
      t($message),
      'plain_text'
    ),
  );
  \Drupal::service('plugin.manager.mail')->mail('ph_commande', 'commande_mail_key', 'touatikarim7@gmail.com', 'en', $params);

}

?>
