<?php

function ph_pharmacie_page_attachments(array &$page) {
  $page['#attached']['library'][] = 'ph_pharmacie/general';
}

function ph_pharmacie_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id)
{
  if ($form_id == "node_circulaire_mdo_form") {
    $current_path = \Drupal::service("path.current")->getPath();
    $parametre = explode("/", $current_path)[1];
    if ($parametre == "mon-profil") {
      $form['actions']['submit']['#submit'][] = 'sauvegarder_circulaire_mdo';
    }
  }
}


function sauvegarder_circulaire_mdo(&$form, \Drupal\Core\Form\FormStateInterface $form_state)
{
  $user = \Drupal\user\Entity\User::load(\Drupal::currentUser()->id());
  $storage = \Drupal::entityTypeManager()->getStorage('profile');
  $profile = $storage->loadByUser($user, 'pharmacie');
  $villeId=$profile->get("field_ville")->getValue()[0]['target_id'];
  $node = \Drupal\node\Entity\Node::load($form_state->getValue('nid'));
  $node->set('field_ville',  $villeId);
  $node->save();
}
